services:
    fastapi:
        build:
            context: .
            dockerfile: IaC/flask/Dockerfile
        ports:
            - "${FASTAPIPORT:-8000:8000}"
            - "5914:5914"
        container_name: "${FASTAPINAME:-fastapi-app}"
        volumes:
            - .:/code
        restart: always
        networks:
            - kallaf
        environment:
            - MONGO_URI=mongodb://${MONGOUSER}:${MONGOPASSWORD}@mongo:27017/${MONGODB}
        env_file:
            - .env
        depends_on:
            - mongo

    mongo:
        image: mongo:4.4
        container_name: "${MONGONAME}"
        restart: always
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGOUSER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGOPASSWORD}
        volumes:
            - mongo_data:/data/db
        networks:
            - kallaf

volumes:
    mongo_data:

networks:
    kallaf:
        driver: bridge
